from extensions import celery_app, mail, db
from flask_mail import Message
from datetime import datetime


@celery_app.task(name="tasks.reports.send_monthly_report")
def send_monthly_report():
    """Generate and email the monthly placement activity report to admin."""
    from models import PlacementDrive, Application, StudentProfile, CompanyProfile
    from flask import current_app

    now   = datetime.utcnow()
    month = now.month - 1 if now.month > 1 else 12
    year  = now.year if now.month > 1 else now.year - 1
    month_name = datetime(year, month, 1).strftime("%B %Y")

    drives = PlacementDrive.query.filter(
        db.extract("month", PlacementDrive.created_at) == month,
        db.extract("year",  PlacementDrive.created_at) == year,
    ).all()

    drive_ids   = [d.id for d in drives]
    apps        = Application.query.filter(Application.drive_id.in_(drive_ids)).all() if drive_ids else []
    selected    = [a for a in apps if a.status == "selected"]
    shortlisted = [a for a in apps if a.status == "shortlisted"]

    rows = ""
    for d in drives:
        d_apps = [a for a in apps if a.drive_id == d.id]
        sel    = sum(1 for a in d_apps if a.status == "selected")
        rows  += f"""
        <tr>
            <td>{d.company.company_name}</td>
            <td>{d.job_title}</td>
            <td>{d.job_type}</td>
            <td>{d.package_lpa or '—'} LPA</td>
            <td>{len(d_apps)}</td>
            <td>{sel}</td>
        </tr>"""

    html_body = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; color: #333; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            th {{ background: #1a3c6e; color: white; padding: 10px; text-align: left; }}
            td {{ padding: 8px 10px; border-bottom: 1px solid #ddd; }}
            tr:nth-child(even) {{ background: #f5f8ff; }}
            .summary-box {{ background: #f0f4ff; border-left: 4px solid #1a3c6e; padding: 15px; margin: 15px 0; border-radius: 4px; }}
            h2 {{ color: #1a3c6e; }}
        </style>
    </head>
    <body>
        <h2>📊 Monthly Placement Activity Report — {month_name}</h2>
        <p>Dear Administrator,</p>
        <p>Here is the placement activity summary for <strong>{month_name}</strong>.</p>

        <div class="summary-box">
            <strong>Summary</strong><br>
            Total Drives Conducted: <strong>{len(drives)}</strong><br>
            Total Applications Received: <strong>{len(apps)}</strong><br>
            Students Shortlisted: <strong>{len(shortlisted)}</strong><br>
            Students Selected: <strong>{len(selected)}</strong><br>
            Total Companies (Active): <strong>{CompanyProfile.query.filter_by(approval_status='approved').count()}</strong><br>
            Total Students Registered: <strong>{StudentProfile.query.count()}</strong>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Company</th><th>Job Title</th><th>Type</th>
                    <th>Package</th><th>Applications</th><th>Selected</th>
                </tr>
            </thead>
            <tbody>
                {rows if rows else '<tr><td colspan="6" style="text-align:center">No drives this month.</td></tr>'}
            </tbody>
        </table>

        <br>
        <small>This report was auto-generated by the Institute Placement Portal on {now.strftime('%d %b %Y %H:%M UTC')}.</small>
    </body>
    </html>
    """

    admin_email = current_app.config.get("ADMIN_EMAIL")
    try:
        msg = Message(
            subject=f"[Placement Portal] Monthly Report — {month_name}",
            recipients=[admin_email],
            html=html_body,
        )
        mail.send(msg)
        return f"Monthly report for {month_name} sent to {admin_email}."
    except Exception as e:
        return f"Report generation succeeded but email failed: {e}"
